name: anshi
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  graphql_parser: ^1.1.1
  graphql_schema: '>=1.0.1 < 2.1.0'
  logging: ^0.11.3
  quiver: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.5.1
