name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  relay_store:
    path: ../
  logging: ^0.11.3
  graphql_parser: ^1.1.1
  graphql_schema: '>=1.0.1 < 2.1.0'


