name: relay_store
description: dart version relay store
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  logging: ^0.11.3
  quiver: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.5.1
